# Change these first
owner: woomymy # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personnal website
    url: https://woomy.be
  - name: Blog
    url: https://blog.woomy.be
  - name: Files storage
    url: https://files.woomy.be
  - name: Gitea
    url: https://gitea.woomy.be
  - name: Bitwarden
    url: https://bitwarden.woomy.be
  - name: NextCloud
    url: https://nextcloud.woomy.be
  - name: FreshRSS
    url: https://rss.woomy.be
  - name: Start page
    url: https://start.woomy.be
  - name: Joplin server
    url: https://joplin.woomy.be
assignees:
  - woomymy
status-website:
  cname: status.woomy.be
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

