# Change these first
owner: woomymy # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personnal website
    url: https://woomy.ovh
  - name: Blog
    url: https://blog.woomy.ovh
  - name: Files storage
    url: https://files.woomy.ovh
  - name: Gitea
    url: https://gitea.woomy.ovh
  - name: Bitwarden
    url: https://bitwarden.woomy.ovh
  - name: NextCloud
    url: https://nextcloud.woomy.ovh
  - name: FreshRSS
    url: https://rss.woomy.ovh
  - name: Debian repository
    url: https://apt.woomy.ovh
  - name: GSI2Zip
    url: https://gsi2zip.woomy.ovh
  - name: Start page
    url: https://start.woomy.ovh
assignees:
  - woomymy
status-website:
  cname: status.woomy.ovh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

